<?php
/* Tripify module for MedLog. Generates trip-reports on the fly! */
require_once("entries.php");

class Tripify 
{
  // Properties
  var $e;
  var $ids;
  var $user;

  // Constructor
  function __construct($user, $ids)
  {
    $this->user = $user;
    $this->ids = $ids;
    $this->e = new EntriesController($user);
  }

  // Builds the header for exported HTML trips
  function generate_html_header()
  {
    $first = $this->e->GetEntryByID($this->ids[0]);
    $res = $first->fetch_assoc();

    // Get the date
    $date = explode(" ", $res["date"])[0];
    ?>
    <h1>Trip Report - <?php echo $date; ?></h1>
    <div id="content">
    <p class="description">Trip report by <?php echo $this->user; ?>.</p>
    <?php
  }

  // Outputs HTML trip report
  function generate_html()
  {
    // Get the first entry
    $fed = $this->e->GetEntryByID($this->ids[0]);
    $fer = $fed->fetch_assoc();

    // Get its time so we have a defined "T+0:00" ($fet)
    $fedt = $fer["date"];
    $fet = explode(" ", $fedt)[1];

    // Convert it to a DateTime object so we can substract
    $to = new DateTime($fet);

    // Now let's get all the other entries.
    echo "<div id=\"tripreport\">\n";
    foreach ($this->ids as $id)
    {
      /* TODO: Also generate a table, including the timing of every ingested drug and its comments. */
      $res = $this->e->GetEntryByID($id);
      $row = $res->fetch_assoc();

      // Get the time
      $dt = $row["date"];
      $ts = explode(" ", $dt)[1];
      $t = new DateTime($ts);

      // Substract from T0
      $tdif = $to->diff($t);
      // Convert to a string
      $time = "T+" . $tdif->format("%H:%I");

      echo "<b>".$time . "</b> (<i>" . $row["dose"] . $row["dose_unit"] . " " . $row["drug"] . "</i>) - " . $row["comment"] . " <br />\n";
    }
    echo "</div>";
  }

  // Generate HTML exported footer
  function generate_html_footer()
  {
    ?>
  </div>
  <p class="footer">Generated by MedLog on <?php echo date("F j, Y, g:i a"); ?>.</p>
  <?php
  }


  /* PLAIN TEXT TRIP REPORTS LOGIC HERE */

    // Builds the header for exported TXT trips
  function generate_txt_header()
  {
    $first = $this->e->GetEntryByID($this->ids[0]);
    $res = $first->fetch_assoc();

    // Get the date
    $date = explode(" ", $res["date"])[0];
    echo "Trip Report - $date\n";
    echo "Trip report by $this->user.\n";
  }

  // Outputs TXT trip report
  function generate_txt()
  {
    // Get the first entry
    $fed = $this->e->GetEntryByID($this->ids[0]);
    $fer = $fed->fetch_assoc();

    // Get its time so we have a defined "T+0:00" ($fet)
    $fedt = $fer["date"];
    $fet = explode(" ", $fedt)[1];

    // Convert it to a DateTime object so we can substract
    $to = new DateTime($fet);

    // Now let's get all the other entries.
    foreach ($this->ids as $id)
    {
      /* TODO: Also generate a table, including the timing of every ingested drug and its comments. */
      $res = $this->e->GetEntryByID($id);
      $row = $res->fetch_assoc();

      // Get the time
      $dt = $row["date"];
      $ts = explode(" ", $dt)[1];
      $t = new DateTime($ts);

      // Substract from T0
      $tdif = $to->diff($t);
      // Convert to a string
      $time = "T+" . $tdif->format("%H:%I");

      echo $time . " (" . $row["dose"] . $row["dose_unit"] . " " . $row["drug"] . ") - " . $row["comment"] . " \n";
    }
  }

  // Generate TXT exported footer
  function generate_txt_footer()
  {
  echo "--------------------------------------------------------------------------\n";
  echo "Generated by MedLog on " . date("F j, Y, g:i a") . ".\n";
  }

}

?>